# config.py
# Общие параметры выхода из сделки — применяются ко всем стратегиям
EXIT_STRATEGY_PARAMS = [

    # --- Параметры детекции уровней ---
    {'key': 'use_pivot_levels', 'label': 'Pivot-уровни', 'default': 0, 'type': int,
     'hint': 'Метод детекции ключевых уровней.\n0 = частотный (статистика касаний цены),\n1 = pivot detection (локальные экстремумы)'},
    {'key': 'pivot_lookback', 'label': 'Lookback пивотов', 'default': 5, 'type': int,
     'hint': 'Кол-во свечей с каждой стороны для подтверждения пивота.\nБольше = менее чувствительно, меньше шума'},

    {'key': 'trailing_sl', 'label': 'Трейлинг-стоп', 'default': 0, 'type': int,
     'hint': 'Перемещаемый стоп-лосс вслед за ценой.\n0 = выключен, 1 = фиксированный отступ, 2 = по MA'},
    {'key': 'trailing_activation', 'label': 'Активация (ATR)', 'default': 0.5, 'type': float,
     'hint': 'Прибыль в ATR, после которой активируется трейлинг.\nНапр. 0.5 = активация при прибыли 0.5*ATR'},
    {'key': 'trailing_offset', 'label': 'Отступ трейлинга (ATR)', 'default': 0.5, 'type': float,
     'hint': 'Расстояние от экстремума цены до трейлинг-стопа в ATR.\nМеньше = теснее, чаще выбивает'},
    {'key': 'trailing_ma_period', 'label': 'Период MA (если тип=2)', 'default': 20, 'type': int,
     'hint': 'Период скользящей средней для трейлинга по MA.\nИспользуется только если тип трейлинга = 2'},
    {'key': 'partial_tp', 'label': 'Частичный TP', 'default': 0, 'type': int,
     'hint': 'Частичное закрытие позиции по достижении целей.\n0 = выключено, 1 = закрыть часть на TP1 и TP2'},
    {'key': 'partial_tp_ratio1', 'label': 'TP1 (ATR)', 'default': 1.5, 'type': float,
     'hint': 'Первый целевой уровень в ATR для частичного закрытия.\nНапр. 1.5 = закрыть часть при прибыли 1.5*ATR'},
    {'key': 'partial_tp_ratio2', 'label': 'TP2 (ATR)', 'default': 3.0, 'type': float,
     'hint': 'Второй целевой уровень в ATR.\nОставшаяся часть позиции закрывается здесь'},
    {'key': 'partial_tp_size1', 'label': 'Доля TP1', 'default': 0.5, 'type': float,
     'hint': 'Доля позиции для закрытия на TP1 (0.0–1.0).\n0.5 = закрыть половину на первом тейке'},

    # --- Multi-timeframe filter ---
    {'key': 'use_mtf_filter', 'label': 'MTF-фильтр', 'default': 0, 'type': int,
     'hint': 'Фильтр по старшему таймфрейму (недельные свечи).\n0 = выключен, 1 = вход только по направлению тренда'},
    {'key': 'mtf_ma_period', 'label': 'MA период (старший ТФ)', 'default': 20, 'type': int,
     'hint': 'Период MA на недельных свечах для определения тренда.\nЦена выше MA = LONG разрешён, ниже = SHORT'},

    # --- Position sizing ---
    {'key': 'position_sizing', 'label': 'Управление размером', 'default': 0, 'type': int,
     'hint': 'Метод расчёта объёма позиции.\n0 = фиксированный % риска, 1 = Kelly Criterion,\n2 = ATR-зависимый (обратно пропорц. волатильности)'},
    {'key': 'kelly_fraction', 'label': 'Доля Kelly', 'default': 0.25, 'type': float,
     'hint': 'Доля от Kelly Criterion (0.0–1.0).\n0.25 = четверть Kelly (консервативно),\n1.0 = полный Kelly (агрессивно)'},
    {'key': 'atr_sizing_mult', 'label': 'ATR-множитель', 'default': 2.0, 'type': float,
     'hint': 'Множитель ATR для волатильного позиционирования.\nВыше ATR = меньше позиция, ниже ATR = больше'},
    {'key': 'exit_assumption', 'label': 'Предположение SL/TP', 'default': 0, 'type': int,
     'hint': 'Когда SL и TP попадают в диапазон [low, high] одной свечи:\n0 = консервативный (SL срабатывает первым),\n1 = оптимистичный (TP первым),\n2 = случайный (50/50, усреднение)'},
]

STRATEGY_REGISTRY = {
    'bounce': {
        'name': 'Отбой от уровней',
        'description': 'Вход при касании ценой уровня и отскоке',
        'func': 'strategy.bounce:check_bounce',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%.\nБольше = агрессивнее, выше просадка'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа, 2.0 = 2 ATR.\nМеньше = теснее стоп, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL = atr_tp/atr_sl определяет R:R'},
            {'key': 'min_hits', 'label': 'Мин. повторов', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня.\nБольше = сильнее уровень, меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров для удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'breakout': {
        'name': 'Пробой уровней',
        'description': 'Вход при пробое уровня с подтверждением закрытием за уровнем',
        'func': 'strategy.breakout:check_breakout',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'breakout_threshold', 'label': 'Порог пробоя (ATR)', 'default': 0.3, 'type': float,
             'hint': 'Множитель ATR — насколько цена должна уйти за уровень для подтверждения пробоя.\nМеньше = чувствительнее к пробоям'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'rsi_levels': {
        'name': 'RSI + Уровни',
        'description': 'Вход при касании уровня с подтверждением по RSI',
        'func': 'strategy.rsi_levels:check_rsi_levels',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'rsi_period', 'label': 'Период RSI', 'default': 14, 'type': int,
             'hint': 'Кол-во свечей для расчёта RSI.\n14 = стандарт, короче = чувствительнее'},
            {'key': 'rsi_oversold', 'label': 'RSI перепроданность', 'default': 30, 'type': float,
             'hint': 'Уровень RSI для перепроданности (сигнал BUY).\n30 = стандарт, ниже = реже сигналы, но надёжнее'},
            {'key': 'rsi_overbought', 'label': 'RSI перекупленность', 'default': 70, 'type': float,
             'hint': 'Уровень RSI для перекупленности (сигнал SELL).\n70 = стандарт, выше = реже сигналы'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'fisher': {
        'name': 'Fisher Transform',
        'description': 'Вход по Fisher-осциллятору Ehlers у уровней поддержки/сопротивления',
        'func': 'strategy.fisher:check_fisher',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'fisher_period', 'label': 'Период Fisher', 'default': 10, 'type': int,
             'hint': 'Кол-во свечей для расчёта Fisher Transform Ehlers.\n10 = стандарт, короче = больше шума'},
            {'key': 'fisher_overbought', 'label': 'Перекупленность', 'default': 1.5, 'type': float,
             'hint': 'Порог перекупленности Fisher.\nСигнал SELL когда Fisher выше этого уровня.\n1.5 = стандарт'},
            {'key': 'fisher_oversold', 'label': 'Перепроданность', 'default': -1.5, 'type': float,
             'hint': 'Порог перепроданности Fisher.\nСигнал BUY когда Fisher ниже этого уровня.\n-1.5 = стандарт'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'trend': {
        'name': 'Trend Detection',
        'description': 'Вход по тренду (TDI + TII от M.H. Pee) у уровней',
        'func': 'strategy.trend:check_trend',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'trend_period', 'label': 'Период тренда', 'default': 20, 'type': int,
             'hint': 'Базовый период для расчёта TDI/TII Pee.\n20 = стандарт, определяет чувствительность тренда'},
            {'key': 'trend_strength', 'label': 'Сила тренда', 'default': 80, 'type': float,
             'hint': 'Минимальный TII для входа (0–100).\n80 = сильный тренд, 50 = умеренный.\nВыше = меньше сигналов, но надёжнее'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'smi': {
        'name': 'SMI (Stochastic Momentum)',
        'description': 'Вход по Stochastic Momentum Index Lambert у уровней',
        'func': 'strategy.smi:check_smi',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'lookback', 'label': 'Lookback период', 'default': 25, 'type': int,
             'hint': 'Кол-во свечей для расчёта SMI Lambert.\n25 = стандарт, короче = чувствительнее'},
            {'key': 'smooth1', 'label': 'Сглаживание 1', 'default': 13, 'type': int,
             'hint': 'Первое сглаживание SMI (EMA).\n13 = стандарт, больше = плавнее'},
            {'key': 'smooth2', 'label': 'Сглаживание 2', 'default': 1, 'type': int},
            {'key': 'smooth3', 'label': 'Сглаживание 3', 'default': 1, 'type': int},
            {'key': 'overbought', 'label': 'Перекупленность', 'default': 40, 'type': float,
             'hint': 'Порог перекупленности SMI.\nСигнал SELL когда SMI выше.\n40 = стандарт'},
            {'key': 'oversold', 'label': 'Перепроданность', 'default': -40, 'type': float,
             'hint': 'Порог перепроданности SMI.\nСигнал BUY когда SMI ниже.\n-40 = стандарт'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'volume_divergence': {
        'name': 'Volume Divergence',
        'description': 'Вход по дивергенции объёма и цены у уровней',
        'func': 'strategy.volumeprice:check_volume_divergence',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'vol_period', 'label': 'Период объёма', 'default': 5, 'type': int,
             'hint': 'Период EMA для расчёта дивергенции объёма и цены.\n5 = стандарт, короче = чувствительнее'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'cog': {
        'name': 'CoG (Center of Gravity)',
        'description': 'Вход по осциллятору Center of Gravity Джона Элерса у уровней',
        'func': 'strategy.cog:check_cog',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'cog_period', 'label': 'Период CoG', 'default': 10, 'type': int,
             'hint': 'Кол-во свечей для расчёта Center of Gravity Ehlers.\n10 = стандарт, короче = чувствительнее'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'tsi': {
        'name': 'TSI (True Strength Index)',
        'description': 'Вход по True Strength Index у уровней поддержки/сопротивления',
        'func': 'strategy.tsi:check_tsi',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'tsi_roc', 'label': 'Период ROC', 'default': 25, 'type': int,
             'hint': 'Первый период сглаживания ROC (Rate of Change).\n25 = стандарт'},
            {'key': 'tsi_smooth', 'label': 'Сглаживание TSI', 'default': 13, 'type': int,
             'hint': 'Второй период сглаживания TSI (Double EMA).\n13 = стандарт'},
            {'key': 'tsi_signal', 'label': 'Сигнальная MA', 'default': 20, 'type': int,
             'hint': 'Период сигнальной линии EMA.\nПересечение сигнальной = точка входа.\n20 = стандарт'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'eco': {
        'name': 'ECO II (Ergodic Candlestick)',
        'description': 'Вход по Ergodic Candlestick Oscillator II Блау у уровней',
        'func': 'strategy.eco:check_eco',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'eco_ave1', 'label': 'Ave1 (C-O)', 'default': 11, 'type': int,
             'hint': 'Первое сглаживание разности Close-Open (EMA).\n11 = стандарт'},
            {'key': 'eco_ave2', 'label': 'Ave2 (H-L)', 'default': 4, 'type': int,
             'hint': 'Первое сглаживание разности High-Low (EMA).\n4 = стандарт'},
            {'key': 'eco_ave3', 'label': 'Ave3 (сигнал)', 'default': 5, 'type': int,
             'hint': 'Период сигнальной EMA Eco II.\n5 = стандарт'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'psychological': {
        'name': 'Psychological Index',
        'description': 'Вход по Psychological Index на экстремумах у уровней',
        'func': 'strategy.psych:check_psychological',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'psych_period', 'label': 'Период индекса', 'default': 12, 'type': int,
             'hint': 'Lookback период для Psychological Index.\nСколько последних свечей анализируется.\n12 = стандарт'},
            {'key': 'psych_overbought', 'label': 'Перекупленность', 'default': 75, 'type': float,
             'hint': 'Верхний порог психологического индекса.\nВыше = рынок перекуплен (SELL).\n75 = стандарт'},
            {'key': 'psych_oversold', 'label': 'Перепроданность', 'default': 25, 'type': float,
             'hint': 'Нижний порог психологического индекса.\nНиже = рынок перепродан (BUY).\n25 = стандарт'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'historical_volatility': {
        'name': 'Historical Volatility',
        'description': 'Вход при низкой волатильности у уровней с трендовым фильтром',
        'func': 'strategy.histvol:check_historical_volatility',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'hv_fast', 'label': 'Быстрая HV', 'default': 10, 'type': int,
             'hint': 'Период быстрой исторической волатильности (StdDev log-доходностей).\n10 = стандарт'},
            {'key': 'hv_slow', 'label': 'Медленная HV', 'default': 100, 'type': int,
             'hint': 'Период медленной исторической волатильности.\n100 = стандарт. Отношение fast/slow определяет сжатие'},
            {'key': 'hv_threshold', 'label': 'Порог HV', 'default': 0.5, 'type': float,
             'hint': 'Отношение HV fast/slow для входа.\n0.5 = вход при низкой волатильности\n(сжатие, предвосхищая расширение)'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'tcf': {
        'name': 'Trend Continuation Factor',
        'description': 'Вход по TCF (M.H. Pee) у уровней поддержки/сопротивления',
        'func': 'strategy.tcf:check_tcf',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'tcf_period', 'label': 'Период TCF', 'default': 35, 'type': int,
             'hint': 'Период суммирования Trend Continuation Factor Pee.\n35 = стандарт, короче = чувствительнее'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'self_adjusting_rsi': {
        'name': 'Self-Adjusting RSI',
        'description': 'Вход по RSI с адаптивными границами Sepiashvili у уровней',
        'func': 'strategy.adjust_rsi:check_self_adjusting_rsi',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'rsi_period', 'label': 'Период RSI', 'default': 14, 'type': int,
             'hint': 'Период расчёта RSI для адаптивных границ.\n14 = стандарт'},
            {'key': 'adjust_k1', 'label': 'K SD метод', 'default': 1.8, 'type': float,
             'hint': 'Множитель стандартного отклонения для SD-метода.\n1.8 = стандарт. Больше = шире границы'},
            {'key': 'adjust_c1', 'label': 'C SMA метод', 'default': 2.0, 'type': float,
             'hint': 'Множитель среднего отклонения для SMA-метода.\n2.0 = стандарт. Больше = шире границы'},
            {'key': 'adjust_method', 'label': 'Метод (1=SD, 2=SMA)', 'default': 1, 'type': int,
             'hint': 'Метод расчёта адаптивных границ RSI.\n1 = стандартное отклонение (SD), 2 = SMA отклонений'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'tether': {
        'name': 'Tether Line',
        'description': 'Вход по системе Tether Line Брайана Стрейна у уровней',
        'func': 'strategy.tether:check_tether',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'tether_period', 'label': 'Период Tether', 'default': 50, 'type': int,
             'hint': 'Период HHV/LLV для расчёта Tether Line.\n50 = стандарт. Определяет ширину канала'},
            {'key': 'tether_vol_period', 'label': 'Период VolOsc', 'default': 7, 'type': int,
             'hint': 'Период SMA для Volume Oscillator.\n7 = стандарт. Фильтр по объёму'},
            {'key': 'tether_ma_fast', 'label': 'MA быстрая', 'default': 25, 'type': int,
             'hint': 'Быстрый период MBO (Moving Bar Oscillator).\n25 = стандарт'},
            {'key': 'tether_ma_slow', 'label': 'MA медленная', 'default': 200, 'type': int,
             'hint': 'Медленный период MBO (Moving Bar Oscillator).\n200 = стандарт. Пересечение быстрой/медленной = тренд'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'regularized_momentum': {
        'name': 'Regularized Momentum',
        'description': 'Вход по Regularized Momentum Satchwell у уровней',
        'func': 'strategy.regularized_mom:check_regularized_momentum',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'reg_period', 'label': 'Период регуляризации', 'default': 21, 'type': int,
             'hint': 'Базовый период Regularized Momentum Satchwell.\n21 = стандарт'},
            {'key': 'reg_d', 'label': 'Константа d', 'default': 0.5, 'type': float,
             'hint': 'Константа регуляризации (штраф за изменение).\n0.5 = стандарт. Больше = плавнее'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'bull_bear_fear': {
        'name': 'Bull/Bear Fear + DX',
        'description': 'Вход по Bull/Bear Fear с фильтром DX у уровней',
        'func': 'strategy.bullbear:check_bull_bear_fear',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'fear_period', 'label': 'Период страха', 'default': 12, 'type': int,
             'hint': 'Период HHV/LLV для Bull/Bear Fear.\n12 = стандарт'},
            {'key': 'dx_period', 'label': 'Период DX', 'default': 10, 'type': int,
             'hint': 'Период Directional Movement Index (DX/ADX).\n10 = стандарт'},
            {'key': 'dx_threshold', 'label': 'Порог DX', 'default': 25, 'type': float,
             'hint': 'Минимальный DX для входа.\n25 = стандарт. Выше = фильтрует нетрендовые рынки'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'j2l': {
        'name': 'J2L System',
        'description': 'Вход по J2L (TSF-LinearReg) Lepreux у уровней',
        'func': 'strategy.j2l:check_j2l',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'j2l_period', 'label': 'Период J2L', 'default': 50, 'type': int,
             'hint': 'Период линейной регрессии (TSF) для J2L.\n50 = стандарт'},
            {'key': 'j2l_trigger', 'label': 'Триггер J2L', 'default': 0.0, 'type': float,
             'hint': 'Уровень триггера для sell (0–0.05).\n0.0 = стандарт. Выше = меньше сигналов'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'ma_relative_strength': {
        'name': 'MA of Rel. Strength',
        'description': 'Вход по пересечению EMA RSI у уровней',
        'func': 'strategy.ma_rs:check_ma_relative_strength',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'ma_rs_rsi', 'label': 'Период RSI', 'default': 14, 'type': int,
             'hint': 'Период расчёта RSI для MA of Relative Strength.\n14 = стандарт'},
            {'key': 'ma_rs_fast', 'label': 'Быстрая EMA', 'default': 10, 'type': int,
             'hint': 'Период быстрой EMA от RSI.\n10 = стандарт'},
            {'key': 'ma_rs_slow', 'label': 'Медленная EMA', 'default': 30, 'type': int,
             'hint': 'Период медленной EMA от RSI.\n30 = стандарт. Пересечение быстрой/медленной = сигнал'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'rmta': {
        'name': 'RMTA (Recursive MA)',
        'description': 'Вход по Recursive Moving Trend Average Meyers у уровней',
        'func': 'strategy.rmta:check_rmta',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'rmta_period', 'label': 'Период RMTA', 'default': 21, 'type': int,
             'hint': 'Lookback период Recursive Moving Trend Average Meyers.\n21 = стандарт'},
            {'key': 'rmta_entry', 'label': 'Порог входа', 'default': 3.0, 'type': float,
             'hint': 'Пороговое значение осциллятора RMTA (0–5).\n3.0 = стандарт. Ниже = чувствительнее'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'fazola': {
        'name': 'Fazola MAROC',
        'description': 'Вход по Fazola MAROC (EMA + ROC) у уровней',
        'func': 'strategy.fazola:check_fazola',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'fazola_ema', 'label': 'Период EMA', 'default': 10, 'type': int,
             'hint': 'Период EMA для трендового фильтра Fazola.\n10 = стандарт'},
            {'key': 'fazola_roc_fast', 'label': 'Быстрый ROC', 'default': 4, 'type': int,
             'hint': 'Быстрый период ROC (Rate of Change).\n4 = стандарт'},
            {'key': 'fazola_roc_slow', 'label': 'Медленный ROC', 'default': 14, 'type': int,
             'hint': 'Медленный период ROC (Rate of Change).\n14 = стандарт'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'inverse_fisher': {
        'name': 'Inv. Fisher + RSI',
        'description': 'Вход по Inverse Fisher Transform от RSI Ehlers у уровней',
        'func': 'strategy.ifisher:check_inverse_fisher',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'ifish_rsi_period', 'label': 'Период RSI', 'default': 5, 'type': int,
             'hint': 'Период RSI для Inverse Fisher Transform.\n5 = стандарт, короче = чувствительнее'},
            {'key': 'ifish_wma_period', 'label': 'Период WMA', 'default': 9, 'type': int,
             'hint': 'Период WMA сглаживания для Inverse Fisher.\n9 = стандарт'},
            {'key': 'ifish_oversold', 'label': 'Перепроданность', 'default': -0.5, 'type': float,
             'hint': 'Уровень перепроданности IFT.\nСигнал BUY ниже этого уровня.\n-0.5 = стандарт'},
            {'key': 'ifish_overbought', 'label': 'Перекупленность', 'default': 0.5, 'type': float,
             'hint': 'Уровень перекупленности IFT.\nСигнал SELL выше этого уровня.\n0.5 = стандарт'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'pro_go': {
        'name': 'Pro Go I (Williams)',
        'description': 'Вход по Professional Index Ларри Уильямса у уровней',
        'func': 'strategy.progo:check_pro_go',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'progo_period', 'label': 'Период Pro Go', 'default': 7, 'type': int,
             'hint': 'Период Professional Index Ларри Уильямса.\n7 = стандарт'},
            {'key': 'progo_ob', 'label': 'Перекупленность', 'default': 75, 'type': float,
             'hint': 'Верхний порог Professional Index.\n75 = стандарт. Выше = перекупленность (SELL)'},
            {'key': 'progo_os', 'label': 'Перепроданность', 'default': 25, 'type': float,
             'hint': 'Нижний порог Professional Index.\n25 = стандарт. Ниже = перепроданность (BUY)'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'siroc': {
        'name': 'Siroc IV',
        'description': 'Вход по Siroc IV Jose Silva у уровней (сигнал/триггер)',
        'func': 'strategy.siroc:check_siroc',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'siroc_prd1', 'label': 'Период 1', 'default': 21, 'type': int,
             'hint': 'Первый период сглаживания Siroc IV.\n21 = стандарт'},
            {'key': 'siroc_prd2', 'label': 'Период 2', 'default': 10, 'type': int,
             'hint': 'Второй период сглаживания Siroc IV.\n10 = стандарт'},
            {'key': 'siroc_prd3', 'label': 'Период 3', 'default': 5, 'type': int,
             'hint': 'Период сигнальной линии Siroc IV.\n5 = стандарт'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'jkl': {
        'name': 'JKL System',
        'description': 'Вход по JKL (взвешенное по StdDev) Kilon у уровней',
        'func': 'strategy.jkl:check_jkl',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'jkl_opt1', 'label': 'Порог', 'default': 0, 'type': float,
             'hint': 'Порог сигнала JKL (оптимизация -15..15).\n0 = нейтральный. Меньше = больше BUY сигналов'},
            {'key': 'jkl_opt2', 'label': 'Короткий период', 'default': 5, 'type': int,
             'hint': 'Короткий период StdDev-взвешивания JKL.\n5 = стандарт'},
            {'key': 'jkl_opt3', 'label': 'Длинный период', 'default': 15, 'type': int,
             'hint': 'Период SMA сигнала JKL.\n15 = стандарт'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'cci_ma': {
        'name': 'CCI + MA',
        'description': 'Вход по пересечению CCI и EMA у уровней',
        'func': 'strategy.cci_ma:check_cci_ma',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'cci_period', 'label': 'Период CCI', 'default': 14, 'type': int,
             'hint': 'Период расчёта CCI (Commodity Channel Index).\n14 = стандарт'},
            {'key': 'cci_ma_period', 'label': 'MA CCI', 'default': 14, 'type': int,
             'hint': 'Период EMA от CCI (сигнальная линия).\n14 = стандарт. Пересечение CCI/MA = сигнал'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'trend_osc': {
        'name': 'Trend + Oscillator',
        'description': 'Вход по SMA + LinRegSlope у уровней',
        'func': 'strategy.trend_osc:check_trend_osc',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'trend_osc_ma', 'label': 'Период SMA', 'default': 20, 'type': int,
             'hint': 'Период SMA трендового фильтра.\n20 = стандарт'},
            {'key': 'trend_osc_slope', 'label': 'Период наклона', 'default': 14, 'type': int,
             'hint': 'Период LinRegSlope (наклон линейной регрессии).\n14 = стандарт'},
            {'key': 'trend_osc_smooth', 'label': 'Сглаживание', 'default': 50, 'type': int,
             'hint': 'Период сглаживания наклона (EMA от LinRegSlope).\n50 = стандарт'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'dinapoli': {
        'name': 'DiNapoli Slow Osc.',
        'description': 'Вход по Preferred Slow Oscillator DiNapoli у уровней',
        'func': 'strategy.dinapoli:check_dinapoli',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'dinapoli_k', 'label': 'Период %K', 'default': 8, 'type': int,
             'hint': 'Период быстрого стохастика (%K).\n8 = стандарт для DiNapoli'},
            {'key': 'dinapoli_d', 'label': 'Сглаживание %D', 'default': 3, 'type': int,
             'hint': 'Первое сглаживание стохастика (%D).\n3 = стандарт'},
            {'key': 'dinapoli_slow', 'label': 'Фин. сглаживание', 'default': 3, 'type': int,
             'hint': 'Второе (финальное) сглаживание стохастика.\n3 = стандарт'},
            {'key': 'dinapoli_ob', 'label': 'Перекупленность', 'default': 70, 'type': float,
             'hint': 'Верхний порог DiNapoli Oscillator.\n70 = стандарт. Выше = перекупленность (SELL)'},
            {'key': 'dinapoli_os', 'label': 'Перепроданность', 'default': 30, 'type': float,
             'hint': 'Нижний порог DiNapoli Oscillator.\n30 = стандарт. Ниже = перепроданность (BUY)'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'coppock': {
        'name': 'Coppock Curve',
        'description': 'Вход по Coppock Curve (WMA ROC) у уровней',
        'func': 'strategy.coppock:check_coppock',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'coppock_roc1', 'label': 'ROC короткий', 'default': 11, 'type': int,
             'hint': 'Короткий период ROC для Coppick Curve.\n11 = стандарт'},
            {'key': 'coppock_roc2', 'label': 'ROC длинный', 'default': 14, 'type': int,
             'hint': 'Длинный период ROC для Coppick Curve.\n14 = стандарт'},
            {'key': 'coppock_wma', 'label': 'WMA период', 'default': 10, 'type': int,
             'hint': 'Период WMA сглаживания Coppick Curve.\n10 = стандарт. Сумма ROC сглаживается WMA'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'dual_thrust': {
        'name': 'Dual Thrust',
        'description': 'Вход по Dual Thrust (канал Open+K*Range от Michael Chalek)',
        'func': 'strategy.dual_thrust:check_dual_thrust',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'dt_lookback', 'label': 'Lookback период', 'default': 20, 'type': int,
             'hint': 'Период для расчёта HH/HC/LL/LC канала.\n20 = стандарт'},
            {'key': 'dt_k1', 'label': 'K1 (покупка)', 'default': 0.7, 'type': float,
             'hint': 'Множитель для верхнего канала (BuyLine).\n0.7 = стандарт. Больше = шире канал, меньше сигналов'},
            {'key': 'dt_k2', 'label': 'K2 (продажа)', 'default': 0.7, 'type': float,
             'hint': 'Множитель для нижнего канала (SellLine).\n0.7 = стандарт. Больше = шире канал, меньше сигналов'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'system_d': {
        'name': 'SystemD',
        'description': 'Вход по SystemD (MA кроссовер + волатильность от George Pruitt)',
        'func': 'strategy.system_d:check_system_d',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'sd_fast_ma', 'label': 'Быстрая MA', 'default': 5, 'type': int,
             'hint': 'Период быстрой EMA для кроссовера.\n5 = стандарт'},
            {'key': 'sd_slow_ma', 'label': 'Медленная MA', 'default': 20, 'type': int,
             'hint': 'Период медленной EMA для кроссовера.\n20 = стандарт'},
            {'key': 'sd_vol_period', 'label': 'Период волатильности', 'default': 10, 'type': int,
             'hint': 'Период SMA для среднего диапазона (волатильность).\n10 = стандарт'},
            {'key': 'sd_vol_factor', 'label': 'Фактор волатильности', 'default': 1.5, 'type': float,
             'hint': 'Порог фильтра волатильности.\n1.5 = стандарт. Диапазон должен быть > фактор*среднее'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'lunar_cycle': {
        'name': 'Lunar Cycle',
        'description': 'Вход по лунным фазам (Full/New Moon от Jose Silva)',
        'func': 'strategy.lunar_cycle:check_lunar_cycle',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'lc_offset', 'label': 'Смещение', 'default': 4.86, 'type': float,
             'hint': 'Астрономическое смещение Julian day для расчёта лунных фаз.\n4.86 = стандарт для рынка РФ'},
            {'key': 'lc_timezone', 'label': 'Часовой пояс', 'default': 3, 'type': int,
             'hint': 'Часовой пояс рынка (-12..+12).\n3 = Москва (UTC+3)'},
            {'key': 'lc_phase_shift', 'label': 'Сдвиг фазы', 'default': 0, 'type': int,
             'hint': 'Дополнительный сдвиг фазы лунного цикла в днях.\n0 = без сдвига'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'dyn_breakout': {
        'name': 'Dynamic BreakOut I',
        'description': 'Вход по Dynamic BreakOut (адаптивный пробой канала + BB)',
        'func': 'strategy.dyn_breakout:check_dyn_breakout',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'dbo_lookback', 'label': 'Базовый lookback', 'default': 20, 'type': int,
             'hint': 'Базовый период адаптивного lookback.\n20 = стандарт. Адаптируется к волатильности'},
            {'key': 'dbo_vol_lookback', 'label': 'Lookback волатильности', 'default': 30, 'type': int,
             'hint': 'Период StdDev для расчёта дельты волатильности.\n30 = стандарт'},
            {'key': 'dbo_floor', 'label': 'Мин. период', 'default': 10, 'type': int,
             'hint': 'Нижняя граница адаптивного периода lookback.\n10 = стандарт'},
            {'key': 'dbo_ceiling', 'label': 'Макс. период', 'default': 40, 'type': int,
             'hint': 'Верхняя граница адаптивного периода lookback.\n40 = стандарт'},
            {'key': 'dbo_bb_mult', 'label': 'Множитель BB', 'default': 2.0, 'type': float,
             'hint': 'Множитель стандартных отклонений для Bollinger Bands.\n2.0 = стандарт (95% интервал)'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'bb_macd': {
        'name': 'BB MACD',
        'description': 'Вход по Bollinger Bands от MACD (пересечение сигнала у BB границ)',
        'func': 'strategy.bb_macd:check_bb_macd',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'bbm_macd_fast', 'label': 'MACD быстрый', 'default': 12, 'type': int,
             'hint': 'Быстрый период EMA для MACD.\n12 = стандарт'},
            {'key': 'bbm_macd_slow', 'label': 'MACD медленный', 'default': 26, 'type': int,
             'hint': 'Медленный период EMA для MACD.\n26 = стандарт'},
            {'key': 'bbm_macd_signal', 'label': 'MACD сигнал', 'default': 9, 'type': int,
             'hint': 'Период сигнальной линии MACD.\n9 = стандарт'},
            {'key': 'bbm_bb_period', 'label': 'BB период', 'default': 20, 'type': int,
             'hint': 'Период Bollinger Bands от MACD.\n20 = стандарт'},
            {'key': 'bbm_bb_mult', 'label': 'BB множитель', 'default': 2.0, 'type': float,
             'hint': 'Множитель StdDev для BB от MACD.\n2.0 = стандарт (95% интервал)'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'base_channel': {
        'name': 'Base Channel',
        'description': 'Вход по Base Channel (канал+StdDev с адаптивной базой)',
        'func': 'strategy.base_channel:check_base_channel',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'bc_period', 'label': 'Lookback период', 'default': 20, 'type': int,
             'hint': 'Период для расчёта канала HHV/LLV.\n20 = стандарт'},
            {'key': 'bc_vol_period', 'label': 'Период волатильности', 'default': 30, 'type': int,
             'hint': 'Период StdDev для адаптивной базы канала.\n30 = стандарт'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние от цены до уровня для входа.\n0.5 = вход только если цена в пределах 0.5*ATR от уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
    'ensemble': {
        'name': 'Ансамбль стратегий',
        'description': 'Голосование нескольких стратегий (majority/any/consensus)',
        'func': 'strategy.ensemble:check_ensemble',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта размера позиции.\nВлияет на кол-во лотов, но не на %-ную доходность'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': '% капитала, рискуемый в одной сделке.\nТипичные значения: 1–3%. Больше = агрессивнее'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса.\n1.0 = 1 ATR от входа. Меньше = теснее, чаще выбивает'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита.\nСоотношение TP/SL (atr_tp/atr_sl) = reward/risk'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна коснуться уровня, чтобы он считался значимым.\nБольше = сильнее уровень, но меньше сигналов'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Макс. кол-во баров удержания позиции.\nЕсли SL/TP не сработали — закрыть по рынку'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку (0.05 = 0.05%).\nУчитывается дважды: вход + выход'},
            {'key': 'sub_strategies', 'label': 'Стратегии (через запятую)', 'default': 'bounce,fisher,trend', 'type': str,
             'hint': 'ID стратегий для ансамбля через запятую.\nНапр.: bounce,fisher,trend,tsi.\nКаждая даёт голос, итог по методу голосования'},
            {'key': 'vote_method', 'label': 'Метод голосования', 'default': 0, 'type': int,
             'hint': 'Метод голосования ансамбля.\n0 = большинство (>50% стратегий),\n1 = любой сигнал (хотя бы одна),\n2 = консенсус (все единогласно)'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int,
             'hint': '0 = по рынку (open следующей свечи),\n1 = лимитный (по цене сигнала)'},
        ]
    },
}


def get_strategy_names():
    return [(k, v['name']) for k, v in STRATEGY_REGISTRY.items()]


def get_strategy_params(strategy_id):
    registry = STRATEGY_REGISTRY.get(strategy_id)
    if not registry:
        return list(EXIT_STRATEGY_PARAMS)
    return list(registry['params']) + list(EXIT_STRATEGY_PARAMS)


def get_strategy_func(strategy_id):
    import importlib
    import logging
    import sys

    registry = STRATEGY_REGISTRY.get(strategy_id)
    if not registry:
        return None
    path = registry.get('func', '')
    if ':' not in path:
        return None
    module_path, func_name = path.split(':')
    try:
        module = importlib.import_module(module_path)
    except ImportError as e:
        logging.getLogger(__name__).error(
            'get_strategy_func: cannot import module=%r strategy_id=%r '
            'sys.path=%r error=%r',
            module_path, strategy_id, sys.path, e,
        )
        raise
    return getattr(module, func_name)


def get_default_params(strategy_id):
    params = get_strategy_params(strategy_id)
    return {p['key']: p['default'] for p in params}
