# config.py
STRATEGY_REGISTRY = {
    'bounce': {
        'name': 'Отбой от уровней',
        'description': 'Вход при касании ценой уровня и отскоке',
        'func': 'strategy.bounce:check_bounce',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта позиции'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': 'Процент капитала, рискуемый в одной сделке'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита'},
            {'key': 'min_hits', 'label': 'Мин. повторов', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна встретиться, чтобы считаться уровнем'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Через сколько свечей закрыть сделку, если не сработали SL/TP'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'breakout': {
        'name': 'Пробой уровней',
        'description': 'Вход при пробое уровня с подтверждением закрытием за уровнем',
        'func': 'strategy.breakout:check_breakout',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта позиции'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': 'Процент капитала, рискуемый в одной сделке'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна встретиться, чтобы считаться уровнем'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Через сколько свечей закрыть сделку, если не сработали SL/TP'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку'},
            {'key': 'breakout_threshold', 'label': 'Порог пробоя (ATR)', 'default': 0.3, 'type': float,
             'hint': 'Множитель ATR — насколько цена должна уйти за уровень'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'rsi_levels': {
        'name': 'RSI + Уровни',
        'description': 'Вход при касании уровня с подтверждением по RSI',
        'func': 'strategy.rsi_levels:check_rsi_levels',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float,
             'hint': 'Начальный капитал для расчёта позиции'},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float,
             'hint': 'Процент капитала, рискуемый в одной сделке'},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float,
             'hint': 'Множитель ATR для стоп-лосса'},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float,
             'hint': 'Множитель ATR для тейк-профита'},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int,
             'hint': 'Сколько раз цена должна встретиться, чтобы считаться уровнем'},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int,
             'hint': 'Через сколько свечей закрыть сделку, если не сработали SL/TP'},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float,
             'hint': 'Комиссия брокера за сделку'},
            {'key': 'rsi_period', 'label': 'Период RSI', 'default': 14, 'type': int,
             'hint': 'Количество свечей для расчёта RSI'},
            {'key': 'rsi_oversold', 'label': 'RSI перепроданность', 'default': 30, 'type': float,
             'hint': 'Уровень RSI для перепроданности (BUY)'},
            {'key': 'rsi_overbought', 'label': 'RSI перекупленность', 'default': 70, 'type': float,
             'hint': 'Уровень RSI для перекупленности (SELL)'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float,
             'hint': 'Множитель ATR — макс. расстояние до уровня'},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'fisher': {
        'name': 'Fisher Transform',
        'description': 'Вход по Fisher-осциллятору Ehlers у уровней поддержки/сопротивления',
        'func': 'strategy.fisher:check_fisher',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'fisher_period', 'label': 'Период Fisher', 'default': 10, 'type': int,
             'hint': 'Количество свечей для расчёта Fisher Transform'},
            {'key': 'fisher_overbought', 'label': 'Перекупленность', 'default': 1.5, 'type': float,
             'hint': 'Порог перекупленности Fisher'},
            {'key': 'fisher_oversold', 'label': 'Перепроданность', 'default': -1.5, 'type': float,
             'hint': 'Порог перепроданности Fisher'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'trend': {
        'name': 'Trend Detection',
        'description': 'Вход по тренду (TDI + TII от M.H. Pee) у уровней',
        'func': 'strategy.trend:check_trend',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'trend_period', 'label': 'Период тренда', 'default': 20, 'type': int,
             'hint': 'Базовый период для расчёта TDI/TII'},
            {'key': 'trend_strength', 'label': 'Сила тренда', 'default': 80, 'type': float,
             'hint': 'Минимальный TII для входа (0-100)'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'smi': {
        'name': 'SMI (Stochastic Momentum)',
        'description': 'Вход по Stochastic Momentum Index Lambert у уровней',
        'func': 'strategy.smi:check_smi',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'lookback', 'label': 'Lookback период', 'default': 25, 'type': int,
             'hint': 'Количество свечей для расчёта SMI'},
            {'key': 'smooth1', 'label': 'Сглаживание 1', 'default': 13, 'type': int,
             'hint': 'Первое сглаживание SMI'},
            {'key': 'smooth2', 'label': 'Сглаживание 2', 'default': 1, 'type': int},
            {'key': 'smooth3', 'label': 'Сглаживание 3', 'default': 1, 'type': int},
            {'key': 'overbought', 'label': 'Перекупленность', 'default': 40, 'type': float,
             'hint': 'Порог перекупленности SMI'},
            {'key': 'oversold', 'label': 'Перепроданность', 'default': -40, 'type': float,
             'hint': 'Порог перепроданности SMI'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'volume_divergence': {
        'name': 'Volume Divergence',
        'description': 'Вход по дивергенции объёма и цены у уровней',
        'func': 'strategy.volumeprice:check_volume_divergence',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'vol_period', 'label': 'Период объёма', 'default': 5, 'type': int,
             'hint': 'Период EMA для объёма и цены'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'cog': {
        'name': 'CoG (Center of Gravity)',
        'description': 'Вход по осциллятору Center of Gravity Джона Элерса у уровней',
        'func': 'strategy.cog:check_cog',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'cog_period', 'label': 'Период CoG', 'default': 10, 'type': int,
             'hint': 'Количество свечей для расчёта Center of Gravity'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'tsi': {
        'name': 'TSI (True Strength Index)',
        'description': 'Вход по True Strength Index у уровней поддержки/сопротивления',
        'func': 'strategy.tsi:check_tsi',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'tsi_roc', 'label': 'Период ROC', 'default': 25, 'type': int,
             'hint': 'Первый период сглаживания ROC'},
            {'key': 'tsi_smooth', 'label': 'Сглаживание TSI', 'default': 13, 'type': int,
             'hint': 'Второй период сглаживания TSI'},
            {'key': 'tsi_signal', 'label': 'Сигнальная MA', 'default': 20, 'type': int,
             'hint': 'Период сигнальной линии EMA'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'eco': {
        'name': 'ECO II (Ergodic Candlestick)',
        'description': 'Вход по Ergodic Candlestick Oscillator II Блау у уровней',
        'func': 'strategy.eco:check_eco',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'eco_ave1', 'label': 'Ave1 (C-O)', 'default': 11, 'type': int,
             'hint': 'Первое сглаживание C-O'},
            {'key': 'eco_ave2', 'label': 'Ave2 (H-L)', 'default': 4, 'type': int,
             'hint': 'Первое сглаживание H-L'},
            {'key': 'eco_ave3', 'label': 'Ave3 (сигнал)', 'default': 5, 'type': int,
             'hint': 'Сигнальная EMA'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'psychological': {
        'name': 'Psychological Index',
        'description': 'Вход по Psychological Index на экстремумах у уровней',
        'func': 'strategy.psych:check_psychological',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'psych_period', 'label': 'Период индекса', 'default': 12, 'type': int,
             'hint': 'Lookback период для Psychological Index'},
            {'key': 'psych_overbought', 'label': 'Перекупленность', 'default': 75, 'type': float,
             'hint': 'Верхний порог психологического индекса'},
            {'key': 'psych_oversold', 'label': 'Перепроданность', 'default': 25, 'type': float,
             'hint': 'Нижний порог психологического индекса'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'historical_volatility': {
        'name': 'Historical Volatility',
        'description': 'Вход при низкой волатильности у уровней с трендовым фильтром',
        'func': 'strategy.histvol:check_historical_volatility',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'hv_fast', 'label': 'Быстрая HV', 'default': 10, 'type': int,
             'hint': 'Период быстрой исторической волатильности'},
            {'key': 'hv_slow', 'label': 'Медленная HV', 'default': 100, 'type': int,
             'hint': 'Период медленной исторической волатильности'},
            {'key': 'hv_threshold', 'label': 'Порог HV', 'default': 0.5, 'type': float,
             'hint': 'Отношение HV fast/slow для входа'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'tcf': {
        'name': 'Trend Continuation Factor',
        'description': 'Вход по TCF (M.H. Pee) у уровней поддержки/сопротивления',
        'func': 'strategy.tcf:check_tcf',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'tcf_period', 'label': 'Период TCF', 'default': 35, 'type': int,
             'hint': 'Период суммирования Trend Continuation Factor'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'self_adjusting_rsi': {
        'name': 'Self-Adjusting RSI',
        'description': 'Вход по RSI с адаптивными границами Sepiashvili у уровней',
        'func': 'strategy.adjust_rsi:check_self_adjusting_rsi',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'rsi_period', 'label': 'Период RSI', 'default': 14, 'type': int,
             'hint': 'Период расчёта RSI'},
            {'key': 'adjust_k1', 'label': 'K SD метод', 'default': 1.8, 'type': float,
             'hint': 'Множитель стандартного отклонения для SD-метода'},
            {'key': 'adjust_c1', 'label': 'C SMA метод', 'default': 2.0, 'type': float,
             'hint': 'Множитель среднего отклонения для SMA-метода'},
            {'key': 'adjust_method', 'label': 'Метод (1=SD, 2=SMA)', 'default': 1, 'type': int,
             'hint': '1 — стандартное отклонение, 2 — SMA отклонений'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'tether': {
        'name': 'Tether Line',
        'description': 'Вход по системе Tether Line Брайана Стрейна у уровней',
        'func': 'strategy.tether:check_tether',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'tether_period', 'label': 'Период Tether', 'default': 50, 'type': int,
             'hint': 'Период HHV/LLV для Tether Line'},
            {'key': 'tether_vol_period', 'label': 'Период VolOsc', 'default': 7, 'type': int,
             'hint': 'Период SMA для Volume Oscillator'},
            {'key': 'tether_ma_fast', 'label': 'MA быстрая', 'default': 25, 'type': int,
             'hint': 'Быстрый период MBO'},
            {'key': 'tether_ma_slow', 'label': 'MA медленная', 'default': 200, 'type': int,
             'hint': 'Медленный период MBO'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'regularized_momentum': {
        'name': 'Regularized Momentum',
        'description': 'Вход по Regularized Momentum Satchwell у уровней',
        'func': 'strategy.regularized_mom:check_regularized_momentum',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'reg_period', 'label': 'Период регуляризации', 'default': 21, 'type': int,
             'hint': 'Базовый период Regularized Momentum'},
            {'key': 'reg_d', 'label': 'Константа d', 'default': 0.5, 'type': float,
             'hint': 'Константа регуляризации'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'bull_bear_fear': {
        'name': 'Bull/Bear Fear + DX',
        'description': 'Вход по Bull/Bear Fear с фильтром DX у уровней',
        'func': 'strategy.bullbear:check_bull_bear_fear',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'fear_period', 'label': 'Период страха', 'default': 12, 'type': int,
             'hint': 'Период HHV/LLV для Bull/Bear Fear'},
            {'key': 'dx_period', 'label': 'Период DX', 'default': 10, 'type': int,
             'hint': 'Период Directional Movement Index'},
            {'key': 'dx_threshold', 'label': 'Порог DX', 'default': 25, 'type': float,
             'hint': 'Минимальный DX для входа'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'j2l': {
        'name': 'J2L System',
        'description': 'Вход по J2L (TSF-LinearReg) Lepreux у уровней',
        'func': 'strategy.j2l:check_j2l',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'j2l_period', 'label': 'Период J2L', 'default': 50, 'type': int,
             'hint': 'Период линейной регрессии J2L'},
            {'key': 'j2l_trigger', 'label': 'Триггер J2L', 'default': 0.0, 'type': float,
             'hint': 'Уровень триггера для sell (0-0.05)'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'ma_relative_strength': {
        'name': 'MA of Rel. Strength',
        'description': 'Вход по пересечению EMA RSI у уровней',
        'func': 'strategy.ma_rs:check_ma_relative_strength',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'ma_rs_rsi', 'label': 'Период RSI', 'default': 14, 'type': int},
            {'key': 'ma_rs_fast', 'label': 'Быстрая EMA', 'default': 10, 'type': int,
             'hint': 'Период быстрой EMA от RSI'},
            {'key': 'ma_rs_slow', 'label': 'Медленная EMA', 'default': 30, 'type': int,
             'hint': 'Период медленной EMA от RSI'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'rmta': {
        'name': 'RMTA (Recursive MA)',
        'description': 'Вход по Recursive Moving Trend Average Meyers у уровней',
        'func': 'strategy.rmta:check_rmta',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'rmta_period', 'label': 'Период RMTA', 'default': 21, 'type': int,
             'hint': 'Lookback период RMTA'},
            {'key': 'rmta_entry', 'label': 'Порог входа', 'default': 3.0, 'type': float,
             'hint': 'Пороговое значение осциллятора (0-5)'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'fazola': {
        'name': 'Fazola MAROC',
        'description': 'Вход по Fazola MAROC (EMA + ROC) у уровней',
        'func': 'strategy.fazola:check_fazola',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'fazola_ema', 'label': 'Период EMA', 'default': 10, 'type': int,
             'hint': 'Период EMA для трендового фильтра'},
            {'key': 'fazola_roc_fast', 'label': 'Быстрый ROC', 'default': 4, 'type': int,
             'hint': 'Быстрый период ROC'},
            {'key': 'fazola_roc_slow', 'label': 'Медленный ROC', 'default': 14, 'type': int,
             'hint': 'Медленный период ROC'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'inverse_fisher': {
        'name': 'Inv. Fisher + RSI',
        'description': 'Вход по Inverse Fisher Transform от RSI Ehlers у уровней',
        'func': 'strategy.ifisher:check_inverse_fisher',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'ifish_rsi_period', 'label': 'Период RSI', 'default': 5, 'type': int,
             'hint': 'Период RSI для Inverse Fisher'},
            {'key': 'ifish_wma_period', 'label': 'Период WMA', 'default': 9, 'type': int,
             'hint': 'Период WMA сглаживания'},
            {'key': 'ifish_oversold', 'label': 'Перепроданность', 'default': -0.5, 'type': float,
             'hint': 'Уровень перепроданности IFT'},
            {'key': 'ifish_overbought', 'label': 'Перекупленность', 'default': 0.5, 'type': float,
             'hint': 'Уровень перекупленности IFT'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
    'pro_go': {
        'name': 'Pro Go I (Williams)',
        'description': 'Вход по Professional Index Ларри Уильямса у уровней',
        'func': 'strategy.progo:check_pro_go',
        'params': [
            {'key': 'capital', 'label': 'Стартовый капитал', 'default': 1000000, 'type': float},
            {'key': 'risk_per_trade', 'label': 'Риск на сделку %', 'default': 2.0, 'type': float},
            {'key': 'atr_sl', 'label': 'ATR для SL', 'default': 1.0, 'type': float},
            {'key': 'atr_tp', 'label': 'ATR для TP', 'default': 2.0, 'type': float},
            {'key': 'min_hits', 'label': 'Мин. повторов уровня', 'default': 5, 'type': int},
            {'key': 'max_hold', 'label': 'Макс. свечей удержания', 'default': 20, 'type': int},
            {'key': 'commission', 'label': 'Комиссия %', 'default': 0.05, 'type': float},
            {'key': 'progo_period', 'label': 'Период Pro Go', 'default': 7, 'type': int,
             'hint': 'Период Professional Index'},
            {'key': 'progo_ob', 'label': 'Перекупленность', 'default': 75, 'type': float,
             'hint': 'Верхний порог Professional Index'},
            {'key': 'progo_os', 'label': 'Перепроданность', 'default': 25, 'type': float,
             'hint': 'Нижний порог Professional Index'},
            {'key': 'level_proximity', 'label': 'Дист. до уровня (ATR)', 'default': 0.5, 'type': float},
            {'key': 'entry_type', 'label': 'Тип входа', 'default': 0, 'type': int},
        ]
    },
}


def get_strategy_names():
    return [(k, v['name']) for k, v in STRATEGY_REGISTRY.items()]


def get_strategy_params(strategy_id):
    registry = STRATEGY_REGISTRY.get(strategy_id)
    if not registry:
        return []
    return list(registry['params'])


def get_strategy_func(strategy_id):
    registry = STRATEGY_REGISTRY.get(strategy_id)
    if not registry:
        return None
    path = registry.get('func', '')
    if ':' not in path:
        return None
    module_path, func_name = path.split(':')
    import importlib
    module = importlib.import_module(module_path)
    return getattr(module, func_name)


def get_default_params(strategy_id):
    params = get_strategy_params(strategy_id)
    return {p['key']: p['default'] for p in params}
